Hashy_hash = {

  "::QueryMethods" => {

    :color     =>  "bg-one",
    :href      =>  "",
    :list      =>

    [{ :name => "count_by_sql(sql)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Querying.html#method-i-count_by_sql" },
     { :name => "create_with(value)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-create_with" },
     { :name => "distinct",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-distinct" },
     { :name => "eager_load",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-eager_load" },
     { :name => "extending",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-extending" },
     { :name => "find_by_sql(sql)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Querying.html#method-i-find_by_sql" },
     { :name => "from",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-from" },
     { :name => "group(*args)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-group" },
     { :name => "having(opts)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-having" },
     { :name => "includes(*args)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-includes" },
     { :name => "joins(*args)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-joins" },
     { :name => "limit(value)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-limit" },
     { :name => "lock",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-lock" },
     { :name => "none",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-none" },
     { :name => "offset(value)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-offset" },
     { :name => "order(*args)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-order" },
     { :name => "preload(*args)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-preload" },
     { :name => "readonly",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-readonly" },
     { :name => "references(table_name)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-references" },
     { :name => "reorder(*args)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-reorder" },
     { :name => "reverse_order",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-reverse_order" },
     { :name => "rewhere(conditions)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-rewhere" },
     { :name => "select(*fields)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-select" },
     { :name => "uniq",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-uniq" },
     { :name => "unscope",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-unscope" },
     { :name => "where",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-where" }]
  },

  "::Persistence" => {
    :color     =>  "bg-two",
    :href      =>  "",
    :list       =>

    [{ :name => "becomes(klass)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-becomes" },
     { :name => "becomes!(klass)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-becomes-21" },
    { :name => "create(attributes)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-create" },
    { :name => "create!(attributes)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-create-21" },
     { :name => "decrement(attribute, by = 1)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-decrement" },
     { :name => "decrement!(attribute, by = 1",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-decrement-21" },
     { :name => "delete",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-delete" },
     { :name => "destroy",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-destroy" },
     { :name => "destroy!",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-destroy" },
     { :name => "destroyed?",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-destroyed-3F" },
     { :name => "incrememnt(attribute, by = 1)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-increment" },

     { :name => "increment!(attribute, by = 1)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-increment-21" },
      { :name => "instantiate(attributes)",
        :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence/ClassMethods.html#method-i-instantiate" },
     { :name => "new_record?",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-new_record-3F" },
     { :name => "persisted?",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-persisted-3F" },
     { :name => "reload(options)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-reload" },
     { :name => "save(*)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-save" },
     { :name => "save!(*)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-save-21" },
     { :name => "toggle(attribute)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-toggle" },
     { :name => "toggle!(attribute)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-toggle-21" },
     { :name => "touch(*names)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-touch" },
     { :name => "update(attributes)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update" },
     { :name => "update!(attribute)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update-21" },
     { :name => "update_attribute(name, value)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_attribute" },
     { :name => "update_attributes(attributes)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_attributes" },
     { :name => "update_attributes!(attributes)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_attributes-21" },
     { :name => "update_column(name, value)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_column" },
     { :name => "update_columns(attributes)",
       :href => "http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_columns" }]
  },

    "::Associations" => {

    :color     =>  "bg-sev",
    :href      =>  "",
    :list      =>

    [{ :name => "belongs_to",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-belongs_to" },
    { :name => "has_and_belongs_to_many",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_and_belongs_to_many" },
    { :name => "has_many",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many" },
    { :name => "has_one",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_one" }]
  },

  "::FinderMethods" => {

    :color     =>  "bg-thr",
    :href      =>  "",
    :list      =>

    [{ :name => "exists?",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-exists-3F"},
    { :name => "fifth",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-fifth" },
    { :name => "fifth!",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-fifth-21" },
    { :name => "find(*args)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find" },
    { :name => "find_by(*args)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_by" },
    { :name => "find_by!(*args)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_by-21" },
    { :name => "find_last",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_last" },
    { :name => "find_nth(index, offset)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_nth" },
    { :name => "find_nth!(index)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_nth-21" },
    { :name => "find_nth_with_limit(offset, limit",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_nth_with_limit" },
    { :name => "find_one(id)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_one" },
    { :name => "find_some(id)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_some" },
    { :name => "find_take",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_take" },
    { :name => "find_with_ids(*ids)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_with_ids" },
    { :name => "first",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-first" },
    { :name => "first!",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-first-21" },
    { :name => "forty_two",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-forty_two" },
    { :name => "forty_two!",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-forty_two-21" },
    { :name => "fourth",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-fourth" },
    { :name => "fourth!",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-fourth-21" },
    { :name => "last",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-last" },
    { :name => "last!",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-last-21" },
    { :name => "second",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-second" },
    { :name => "second!",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-second-21" },
    { :name => "take",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-take" },
    { :name => "take!",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-take-21" },
    { :name => "third",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-third" },
    { :name => "third!",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-third-21" }]
  },

    "::Relation" => {

    :color     =>  "bg-fiv",
    :href      =>  "",
    :list      =>

    [{ :name => "==",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-3D-3D" },
    { :name => "any?",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-any-3F" },
    { :name => "blank?",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-blank-3F" },
    { :name => "build(*args)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-build" },
    { :name => "create(*args)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-create" },
    { :name => "create!(*args)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-create-21" },
    { :name => "delete(id)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-delete" },
    { :name => "delete_all",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-delete_all" },
    { :name => "destroy",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-destroy" },
    { :name => "destroy_all",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-destroy_all" },
    { :name => "eager_loading?",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-eager_loading-3F" },
    { :name => "empty?",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-empty-3F" },
    { :name => "encode_with(encoder)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-encode_with" },
    { :name => "explain",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-explain" },
    { :name => "find_or_create_by(attributes, &block)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-find_or_create_by" },
    { :name => "find_or_create_by!(attributes, &block)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-find_or_create_by-21" },
    { :name => "find_or_initialize_by(attributes, &block)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-find_or_initialize_by" },
    { :name => "initialize_copy(other)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-initialize_copy" },
    { :name => "inspect",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-inspect" },
    { :name => "joined_includes_variables",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-joined_includes_values" },
    { :name => "load",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-load" },
    { :name => "many?",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-many-3F" },
    { :name => "new(*args, &block)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-new" },
    { :name => "pretty_print(q)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-pretty_print" },
    { :name => "reload",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-reload" },
    { :name => "reset",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-reset" },
    { :name => "scpoe_for_create",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-scope_for_create" },
    { :name => "scoping",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-scoping" },
    { :name => "size",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-size" },
    { :name => "to_a",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-to_a" },
    { :name => "to_sql",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-to_sql" },
    { :name => "uniq_value",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-uniq_value" },
    { :name => "update",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-update" },
    { :name => "update_all(updates)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-update_all" },
    { :name => "values",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-values" },
    { :name => "where_values_hash",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-where_values_hash" }]
  },



  "::ModelSchema" => {

    :color     =>  "bg-fou",
    :href      =>  "",
    :list      =>

    [{ :name => "column_defaults",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-column_defaults" },
    { :name => "column_names",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-column_names" },
    { :name => "content_columns",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-content_columns" },
    { :name => "inheritence_column",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-inheritance_column" },
    { :name => "inheritence_column=(value)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-inheritance_column-3D" },
    { :name => "quoted_table_name",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-quoted_table_name" },
    { :name => "reset_column_information",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-reset_column_information" },
    { :name => "sequence_name",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-sequence_name" },
    { :name => "sequence_name=(value)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-sequence_name-3D" },
    { :name => "table_exists?",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-table_exists-3F" },
    { :name => "table_name",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-table_name" },
    { :name => "table_name=(value)",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-table_name-3D" }]
  },


"::SchemaStatments" => {

    :color     =>  "bg-six",
    :href      =>  "",
    :list      =>

   [{ :name => "add_belongs_to",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_belongs_to" },
    { :name => "add_column",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_column" },
    { :name => "add_foreign_key",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_foreign_key" },
    { :name => "add_index",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_index" },
    { :name => "add_index_sort_order",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_index_sort_order" },
    { :name => "add_reference",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_reference" },
    { :name => "add_timestamps",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_timestamps" },
    { :name => "assume_migrated_upto_version",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-assume_migrated_upto_version" },
    { :name => "change_column",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-change_column" },
    { :name => "change_column_default",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-change_column_default" },
    { :name => "change_column_null",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-change_column_null" },
    { :name => "change_table",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-change_table" },
    { :name => "column_exists?",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-column_exists-3F" },
    { :name => "columns",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-columns" },
    { :name => "create_join_table",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-create_join_table" },
    { :name => "create_table",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-create_join_table" },
    { :name => "drop_join_table",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-create_join_table" },
    { :name => "drop_table",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-drop_table" },
    { :name => "foreign_keys",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-foreign_keys" },
    { :name => "index_exists?",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-index_exists-3F" },
    { :name => "index_name_exists?",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-index_name_exists-3F" },
    { :name => "index_name_for_remove",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-index_name_for_remove" },
    { :name => "initialize_schema_migrations_table",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-initialize_schema_migrations_table" },
    { :name => "native_database_types",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-native_database_types" },
    { :name => "options_include_default?",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-options_include_default-3F" },
    { :name => "quoted_columns_for_index",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-quoted_columns_for_index" },
    { :name => "remove_belongs_to",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_belongs_to" },
    { :name => "remove_column",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_column" },
    { :name => "remove_columns",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_columns" },
    { :name => "remove_foreign_key",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_foreign_key" },
    { :name => "remove_index",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_index" },
    { :name => "remove_reference",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_reference" },
    { :name => "remove_timestamps",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_timestamps" },
    { :name => "rename_column",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-rename_column" },
    { :name => "rename_column_indexes",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-rename_column_indexes" },
    { :name => "rename_index",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-rename_index" },
    { :name => "rename_table",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-rename_table" },
    { :name => "rename_table_indexes",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-rename_table_indexes" },
    { :name => "table_alias_for?",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-table_alias_for" },
    { :name => "table_exists?",
      :href => "http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-table_exists-3F" }]
  },





}
